[package]
name = "currency"
version = "0.3.0"
authors = ["tberry@student.neumont.edu"]
description = "A library written in Rust for representing Currencies."
repository = "https://github.com/Tahler/rust-lang-currency"
documentation = "http://tyborg.me/rust_docs/currency/currency/index.html"
keywords = ["Currency", "Money"]
license = "MPL-2.0"

[dependencies]
num = "0.1.32"
regex = "0.1.41"
